apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig


metadata:
  name: shopgpt
  region: eu-west-1
  version: "1.29"


nodeGroups:
  - name: ng-1
    instanceType: m5.large
    desiredCapacity: 10
    volumeSize: 100